### ISSUE TITLE
Can't download sample sheets

### ISSUE THREAD

**Issue by dpryan79** [maxplanck-ie/parkour#29]
This appears to be related to the code refactoring. A URL of `api/flowcell/download_sample_sheet/`can't get routed and results in a 404 error. I imagine that there are a couple of different ways to fix this. I've temporarily added the following to `wui/api.py`:

    router.register(r'flowcell', FlowcellViewSet, base_name='flowcell')

That works, but since I haven't gone through the code to see if the `FlowcellViewSet` is doing anything else I'm not sure that this is side-effect free.

**Comment by anatskiy** [comment]
I've already fixed this! I'll upload the changes soon.

**Comment by anatskiy** [comment]
fixed in 8b725137a66aec5ccd62b20c03d9d956bf1b3121
