### ISSUE TITLE
nice to have manual/tutorial

### ISSUE THREAD

**Issue by mijgmak** [maxplanck-ie/parkour#32]
We are looking for NGS LIMS system for our NGS core facility and I've found parkour. Great job with a lot of potential. It would be nice to have a manual and tutorial for using parkour.

**Comment by dpryan79** [comment]
I believe that's one of the things @anatskiy is working on.

@anatskiy Is any of the stuff that you or Ulrike has written available online?

**Comment by bgruening** [comment]
@mijgmak we are currently working on this. In the meantime please feel free to ask Q.

**Comment by mijgmak** [comment]
@bgruening Thank's, I'll do it
