### ISSUE TITLE
Configuration E-mail send server and samplesheet generation

### ISSUE THREAD

**Issue by mijgmak** [maxplanck-ie/parkour#40]
Where can I set email send server settings (name, port, protocol) and the read length for samplesheet generator in parkour

Regards

**Comment by dpryan79** [comment]
Have a look at `wui/settings/base.py` https://github.com/maxplanck-ie/parkour/blob/develop/wui/settings/base.py#L139-L141

**Comment by dpryan79** [comment]
You'll want to change `ADMINS` too, since they get error reports.
