### ISSUE TITLE
IntegrityError at library_sample_shared_indexi7_pkey

### ISSUE THREAD

**Issue by mijgmak** [maxplanck-ie/parkour#43]
I ve imported indexi7 tables to postgresql database per command line. If I try now to add index to parkour shared tables I get this error massage:
"IntegrityError at /admin/library_sample_shared/indexi7/add/
duplicate key value violates unique constraint "library_sample_shared_indexi7_pkey"
DETAIL:  Key (id)=(8) already exists."
Parkour tried to use an existing key in database?

**Comment by dpryan79** [comment]
Was there a missing key (e.g., key 1 or 5 or something like that wasn't present)? That's my only guess as to how this could happen.
