### ISSUE TITLE
Centos 7.4 problem install parckour

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [maxplanck-ie/parkour#44]
I try to install parkour using the command describe on the help. I have this error:
S```
uccessfully built django-authtools django-admin-list-filter-dropdown sphinx-autobuild fpdf python-docx django-monthfield watchdog pathtools PyYAML tornado port-for MarkupSafe prometheus-client pandocfilters backcall simplegeneric
Installing collected packages: pytz, Django, django-authtools, djangorestframework, django-admin-list-filter-dropdown, six, django-extensions, psycopg2, dj-database-url, certifi, chardet, idna, urllib3, requests, alabaster, docutils, imagesize, MarkupSafe, Jinja2, pyparsing, packaging, snowballstemmer, Pygments, babel, sphinxcontrib-websupport, Sphinx, PyYAML, argh, pathtools, watchdog, tornado, port-for, livereload, sphinx-autobuild, sphinx-rtd-theme, xlwt, fpdf, numpy, python-dateutil, pandas, jsonschema, ipython-genutils, decorator, traitlets, jupyter-core, nbformat, pyzmq, jupyter-client, pickleshare, backcall, ptyprocess, pexpect, wcwidth, prompt-toolkit, simplegeneric, parso, jedi, ipython, ipykernel, terminado, pandocfilters, entrypoints, testpath, mistune, webencodings, html5lib, bleach, nbconvert, prometheus-client, Send2Trash, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-console, jupyter, requests-toolbelt, boto, bioblend, lxml, python-docx, gunicorn, django-monthfield
Successfully installed Django-1.11.14 Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.13 Pygments-2.2.0 Send2Trash-1.5.0 Sphinx-1.7.6 alabaster-0.7.11 argh-0.26.2 babel-2.6.0 backcall-0.1.0 bioblend-0.11.0 bleach-2.1.3 boto-2.49.0 certifi-2018.4.16 chardet-3.0.4 decorator-4.3.0 dj-database-url-0.5.0 django-admin-list-filter-dropdown-1.0.1 django-authtools-1.6.0 django-extensions-2.1.0 django-monthfield-0.1.0 djangorestframework-3.8.2 docutils-0.14 entrypoints-0.2.3 fpdf-1.7.2 gunicorn-19.9.0 html5lib-1.0.1 idna-2.7 imagesize-1.0.0 ipykernel-4.8.2 ipython-6.4.0 ipython-genutils-0.2.0 ipywidgets-7.3.0 jedi-0.12.1 jsonschema-2.6.0 jupyter-1.0.0 jupyter-client-5.2.3 jupyter-console-5.2.0 jupyter-core-4.4.0 livereload-2.5.2 lxml-4.2.3 mistune-0.8.3 nbconvert-5.3.1 nbformat-4.4.0 notebook-5.6.0 numpy-1.15.0 packaging-17.1 pandas-0.23.3 pandocfilters-1.4.2 parso-0.3.1 pathtools-0.1.2 pexpect-4.6.0 pickleshare-0.7.4 port-for-0.3.1 prometheus-client-0.3.0 prompt-toolkit-1.0.15 psycopg2-2.7.5 ptyprocess-0.6.0 pyparsing-2.2.0 python-dateutil-2.7.3 python-docx-0.8.6 pytz-2018.5 pyzmq-17.1.0 qtconsole-4.3.1 requests-2.19.1 requests-toolbelt-0.8.0 simplegeneric-0.8.1 six-1.11.0 snowballstemmer-1.2.1 sphinx-autobuild-0.7.1 sphinx-rtd-theme-0.4.0 sphinxcontrib-websupport-1.1.0 terminado-0.8.1 testpath-0.3.1 tornado-5.1 traitlets-4.3.2 urllib3-1.23 watchdog-0.8.3 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.3.0 xlwt-1.3.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 53f5317b1b10
 ---> 8ee47e4303c9
Step 7/9 : ENV DJANGO_SETTINGS_MODULE "wui.settings.prod"
 ---> Running in eeef8a2fbc7e
Removing intermediate container eeef8a2fbc7e
 ---> 456a5e552fe0
Step 8/9 : ENV SECRET_KEY "5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d"
 ---> Running in 2c33b8cdea1c
Removing intermediate container 2c33b8cdea1c
 ---> b40be691c4e7
Step 9/9 : RUN python manage.py collectstatic -v 0 --noinput
 ---> Running in 261744196a23
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.filters import (
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/filters.py", line 10, in <module>
    from django.contrib.admin.options import IncorrectLookupParameters
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/options.py", line 13, in <module>
    from django.contrib.admin import helpers, widgets
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
ERROR: Service 'parkour-web' failed to build: The command '/bin/sh -c python manage.py collectstatic -v 0 --noinput' returned a non-zero code: 1
```

**Comment by bgruening** [comment]
@bioinfo-dirty-jobs can you give us the command which you are using?
It seems you try to build the Docker image is this correct? And you try to do this on CentOS? The error is Django related and not parkour specific as far as I can tell. Mabye related to the new python version which you are using?

**Comment by bioinfo-dirty-jobs** [comment]
@bgruening 
Thanks so much for the help.. 
I try to follow the  installation described on the  this site (https://parkour.readthedocs.io/installation.html#quick-start). 
sudo /usr/local/bin/docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

**Comment by bgruening** [comment]
Can you check out the latest repository and try again please :)

**Comment by bioinfo-dirty-jobs** [comment]
@bgruening  Thanks so much.. seem that step resolved. Now I have the problem on the certification..
Could you please help on how to prepare that cerrtification on centos?
I don't understand which .crt.. we need to use.

**Comment by dpryan79** [comment]
The .crt file is needed to use https to connect. Whether you use a self-signed certificate or one signed by either your IT department or some signing authority is then up to you.
