### ISSUE TITLE
How can I upload additional files to pools

### ISSUE THREAD

**Issue by mijgmak** [maxplanck-ie/parkour#47]
I'd like to upload  files, like BA *.pdf plots etc. to pools in parkour. How can I do that as admin or staff

**Comment by mijgmak** [comment]
You mean Request=Project ? if so, it works for us. I found this function in "Requests", but when I tried to upload as admin I got "server error" and "WARNING" in log: [WARNING] [02/Aug/2018 14:33:08] [/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py:124]: log_message(): "POST /request/upload_files/ HTTP/1.1" 404 4553

**Comment by dpryan79** [comment]
Yes, Request==Project, sorry about that. Does the parkour user have write permissions inside the docker storage volume?

**Comment by mijgmak** [comment]
I use the manual installation of parkour. The parkour user have full write permissions in storage. The upload of signed request form is working and stored in /media/deep_sequencing_requests/2018/07/...

**Comment by dpryan79** [comment]
Interesting, so do you only receive the error for files other than signed requests or do you get the error regardless but the files are still uploaded?

**Comment by dpryan79** [comment]
Can you post either your nginx.conf or the parkour file under nginx/sites-enabled?

**Comment by dpryan79** [comment]
The requests are placed in `/media/deep_sequencing_requests` and all other files in `/media/request_files`. There's also a `/media/invoicing` in case you using Parkour for generating invoices. Perhaps the request_files folder doesn't exist?

In hindsight it may have made more sense to separate requests by request ID, I agree, though at least this way we can trivially remove all files older than X years (granted, that's not exactly difficult with `find` on the command line).

**Comment by mijgmak** [comment]
You are right, the request_files and invoicing  folder doesn't exist. I have to add these paths to config file?

**Comment by dpryan79** [comment]
Try just creating those folders and see if that solves the problem. Otherwise I'll double check our config file and see what you might need to change.

**Comment by mijgmak** [comment]
The folders are missing in docker version too.

**Comment by dpryan79** [comment]
Hmm, I wonder if we manually made those directories at some point. If that's necessary I'll update the installation instructions.

**Comment by dpryan79** [comment]
FYI, on the dockerized version `media` is empty to begin with and the various folders created as needed (I just tested this). This suggests that parkour doesn't have permission to create folders in your `/media` folder.

**Comment by mijgmak** [comment]
Unfortunately I got the same error after creating the missing folders, but the generation of invoicing report is working. I wonder in dockerized version shouldn't be a permission problem? Is it possible to activate a more detailed logging in parkour for troubleshooting?

**Comment by dpryan79** [comment]
Can you `chmod -R 777` on that directory and see if that fixes things? I'm not aware of any more detailed logging. @anatskiy ?

**Comment by mijgmak** [comment]
I ve updated parkour with  git clone, now uploading is working. I saw you have changed some files to fix request upload 2 month ago. My parkour wasn't up to date

**Comment by dpryan79** [comment]
Ah, guess that was the problem then. Glad it's working! Can we close this issue then?

**Comment by mijgmak** [comment]
Yes you can close this issue. Many thanks!
