### ISSUE TITLE
Dropdown window "Library Type" not working

### ISSUE THREAD

**Issue by FrancescoFerrari88** [maxplanck-ie/parkour#48]
When I add a Sample and ask for RELACS high-throughput, the drop-down window "Library Type" does not open nor accepts any written input. As the record is mandatory, I cannot proceed with my request

![schermata 2018-08-03 alle 11 37 30](https://user-images.githubusercontent.com/30049504/43636447-638589f4-9712-11e8-864f-5db536171306.png)

**Comment by bioinfo-dirty-jobs** [comment]
@FrancescoFerrari88 I have the same problem ...seem you need to create the value on the  Django administation   page...
