### ISSUE TITLE
Flowcells run

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [maxplanck-ie/parkour#49]
I  want to import on  parkour previous runs. How can do this task? If I start with  library  the flowcell are linked with the date of the machine. I mean If I try to import  run on 16 july  they import as today date..

**Comment by dpryan79** [comment]
The simplest method would be to just change the dates in the database (possibly via the admin interface for django). We haven't bothered to import our old datasets, so our own instance has libraries starting a year ago.
