### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Liripo** [maxplanck-ie/parkour#63]
according to[parkour](https://parkour.readthedocs.io/installation.html#configure-the-database)，I have an error
```python
django.db.utils.OperationalError: fe_sendauth: no password supplied
```
I don't how to solve.

**Comment by thomasmanke** [comment]
You might want to try the docker-based installation: https://github.com/maxplanck-ie/docker-parkour/

Please be aware of the file parkour.env. there you should set all relevant variables.
