### ISSUE TITLE
Introduction to the API

### ISSUE THREAD

**Issue by cohenp05** [maxplanck-ie/parkour#65]
Hello,

I am working on implementing a LIMS system for our single cell genomics lab, and Parkour seems like a really great option for managing our library preps, etc. I need to customize some things (add fields for preparation steps, modify the index generator to allow single i5 indexing, disable requirements for PI approval of requests), but I'm not sure how to get started with the API to modify these things. Can you point anywhere to get started with these things? I have some  python, html, and bash scripting experience (very little for SQL but could learn quickly) mostly for applications to data science, but I'm just not sure how to begin to tackle this as I'm not a software engineer. 

Thank you!

**Comment by bgruening** [comment]
Hi @cohenp05!

Have you seen the documentation at https://parkour.readthedocs.io, there is also a section about the API. Parkour is built on-top of Django, so if you are familiar with Django or get yourself familiar this will also help.
